version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_auth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - user_auth-network

volumes:
  postgres-data:

networks:
  user_auth-network:
